language: python
python:
  - "3.8"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python -c "pass"
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_TOKEN
  on:
    branch: master