language: python
python:
- '3.8'
cache: pip
install:
- pip install -r requirements.txt
script:
- python -c "pass"
before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku:git
  api_key: $HEROKU_API_KEY
  app:
    master: rtlog-validator
    hml: rtlog-validator-hml
  edge: true
#  on:
#    branch: master
