language: python
python:
- '3.8'
cache: pip
install:
- pip install -r requirements.txt
script:
- python -c "pass"
deploy:
  provider: heroku
  api_key:
    secure: dm9WH/wm9AT4b068rLBdYF5L0b77cMLkqq3Ug4xt5V51GQ0aCxVYR33yBMtESH6GOKBx7bYITd38MtXnvt8ENxGcfHwK1+0cshh9VktxO94OrzXUbFH6+O1ZSGiCg9bLre1FEu6FxIFuZO7B0biGrCOSvM+Yne8fQt0HywNbn8e6VzzqsMpfuAWGI28lNGQbtnJGhS8OzmKYuzhrKV2FMOacYGqaLGgam9JsaW4YE63R4LBwATju81oKU5ejrlqCzxChZL/jQgCs3Ta9a7svQC7OimxkUXRqNs99CaGVPSo/YMsux8XnwxmBzJdjfzkSoWt6oigzMMWyY+6rUtCqXcXAq8SMkfT3TL7tIXDpFju1fqANLHkrk2pRM0Tc318LAjGeta7Wen5q9VTijSKdkKUqaeGJTLRfpXkSKsnc/3vy/yG/fI3B/nn2MxLlRuS52/YKOxz53HUff60JNzGGrdRMWhRZyFltQAo8CbLM3ya1tzQ0njSpjs/uy8fdfqfAzHTfaP3KsSruAtl3sR3CSX4WsGyzNgdoKE/sleTLOYNSGXi+p+MP5rCwL+xdmbCb33W/M9I4R2oqS1FhY+gFZmuIDZ/6XRe0STxmg2ydRJdRfWPoarQ6I6K7QQE0v4foPCe3gFEaN6qv4XLgCBBXq/XarKW9NqkAYBOA9Rza+kQ=
    app: rtlog-validator
  true:
    branch: master
